# Railway — SGRH Pro (Laravel)
# Dans Railway : Root Directory = RH_CNSS/sgrh-pro

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
