"""
Rôle du fichier:
Expose les modèles de données SQLAlchemy pour simplifier les imports dans le reste du projet.
"""

from app.models.db_models import (
    ActivityLog,
    Attendance,
    BiometricDevice,
    Contract,
    ContractType,
    Department,
    Employee,
    EmployeeSkill,
    EmployeeStatus,
    Holiday,
    JobApplication,
    JobOffer,
    Leave,
    MedicalLeave,
    Message,
    Notification,
    Payroll,
    PerformanceEvaluation,
    Permission,
    Role,
    Skill,
    SystemParameter,
    Training,
    TrainingEnrollment,
    User,
)

__all__ = [
    "User",
    "Role",
    "Permission",
    "Department",
    "Employee",
    "Message",
    "Payroll",
    "Attendance",
    "Leave",
    "Contract",
    "ActivityLog",
    "EmployeeStatus",
    "ContractType",
    "BiometricDevice",
    "Training",
    "TrainingEnrollment",
    "Skill",
    "EmployeeSkill",
    "PerformanceEvaluation",
    "MedicalLeave",
    "Notification",
    "JobOffer",
    "JobApplication",
    "SystemParameter",
    "Holiday",
]
